import axiosClient from 'utils/axios';

const providerContractsService = {
  getProviderContracts,
  getDeletedProviderContracts,
  searchProviderContracts,
  getProviderContractStats,
  getExpiringContracts,
  getContractsByStatus,
  getProviderContractById,
  getProviderContractByCode,
  getContractsByProvider,
  getActiveContractByProvider,
  createProviderContract,
  updateProviderContract,
  restoreProviderContract,
  deleteProviderContract,
  activateContract,
  suspendContract,
  terminateContract,
  getContractPricingItems,
  searchContractPricingItems,
  getContractPricingStats,
  getPricingItemById,
  addPricingItem,
  addBulkPricingItems,
  updatePricingItem,
  deletePricingItem,
  deleteAllPricingItems,
  downloadPricingTemplate,
  uploadContractPricingExcel,
  getMyActiveContract,
  getMyContractServices,
  addMyContractPricing,
  getAllContractedServices,
  importPriceListPreview,
  confirmPriceListImport
};

export default providerContractsService;
