-- Restore the unified medical catalog tables required by the active JPA model.
-- These tables were referenced by the application after the consolidated
-- migration history stopped creating them.

CREATE TABLE IF NOT EXISTS medical_services (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(50)  NOT NULL,
    status       VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    name         VARCHAR(200) NOT NULL,
    name_ar      VARCHAR(255),
    name_en      VARCHAR(255),
    category_id  BIGINT,
    specialty_id BIGINT,
    description  VARCHAR(500),
    base_price   NUMERIC(10,2),
    cost         NUMERIC(15,2),
    requires_pa  BOOLEAN      NOT NULL DEFAULT true,
    is_master    BOOLEAN      NOT NULL DEFAULT false,
    deleted      BOOLEAN      NOT NULL DEFAULT false,
    deleted_at   TIMESTAMP,
    deleted_by   BIGINT,
    active       BOOLEAN      NOT NULL DEFAULT true,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_medical_services_code UNIQUE (code),
    CONSTRAINT chk_medical_services_status
        CHECK (status IN ('DRAFT', 'ACTIVE', 'ARCHIVED')),
    CONSTRAINT fk_medical_services_category
        FOREIGN KEY (category_id) REFERENCES medical_categories(id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_medical_services_category
    ON medical_services(category_id);
CREATE INDEX IF NOT EXISTS idx_medical_services_active
    ON medical_services(active, deleted);
CREATE INDEX IF NOT EXISTS idx_medical_services_name
    ON medical_services(name);

CREATE SEQUENCE IF NOT EXISTS medical_service_category_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE IF NOT EXISTS medical_service_categories (
    id          BIGINT PRIMARY KEY DEFAULT nextval('medical_service_category_seq'),
    service_id  BIGINT       NOT NULL,
    category_id BIGINT       NOT NULL,
    context     VARCHAR(20)   NOT NULL DEFAULT 'ANY',
    is_primary  BOOLEAN       NOT NULL DEFAULT false,
    active      BOOLEAN       NOT NULL DEFAULT true,
    created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by  VARCHAR(255),

    CONSTRAINT fk_msc_service
        FOREIGN KEY (service_id) REFERENCES medical_services(id) ON DELETE CASCADE,
    CONSTRAINT fk_msc_category
        FOREIGN KEY (category_id) REFERENCES medical_categories(id) ON DELETE RESTRICT,
    CONSTRAINT uq_msc_service_category_context
        UNIQUE (service_id, category_id, context)
);

CREATE INDEX IF NOT EXISTS idx_msc_service_context
    ON medical_service_categories(service_id, context);

CREATE UNIQUE INDEX IF NOT EXISTS uq_msc_primary_per_context
    ON medical_service_categories(service_id, context)
    WHERE is_primary = true AND active = true;

CREATE SEQUENCE IF NOT EXISTS ent_service_alias_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE IF NOT EXISTS ent_service_aliases (
    id                 BIGINT PRIMARY KEY DEFAULT nextval('ent_service_alias_seq'),
    medical_service_id BIGINT       NOT NULL,
    alias_text         VARCHAR(255) NOT NULL,
    locale             VARCHAR(10)  NOT NULL DEFAULT 'ar',
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by         VARCHAR(255),

    CONSTRAINT fk_ent_service_alias_service
        FOREIGN KEY (medical_service_id) REFERENCES medical_services(id) ON DELETE CASCADE,
    CONSTRAINT uq_ent_service_alias
        UNIQUE (medical_service_id, alias_text, locale)
);

CREATE INDEX IF NOT EXISTS idx_ent_service_alias_text
    ON ent_service_aliases(alias_text);
