package com.waad.tba.modules.semantic.entity.enums;

public enum ProcedureType {
    CONSULTATION,
    DIAGNOSTIC_TEST,
    LAB_TEST,
    IMAGING,
    MEDICATION,
    MEDICAL_DEVICE,
    MINOR_SURGERY,
    MAJOR_SURGERY,
    INPATIENT_STAY,
    DELIVERY,
    PHYSIOTHERAPY_SESSION,
    DENTAL_ROUTINE,
    DENTAL_ADVANCED,
    OPTICAL_EXAM,
    OPTICAL_DEVICE,
    ANESTHESIA,
    AMBULANCE,
    HOME_NURSING,
    UNKNOWN
}
